### ISSUE TITLE
showPromptIfNecessary doesn't show the prompt

### ISSUE THREAD

**Issue by MihaiSvet** [UrbanApps/UAAppReviewManager#27]
showPromptIfNecessary doesn't show the prompt.

Here's my code:
```
+(void)initialize{
    [AppDelegate setupUAAppReviewManager];
}

+(void)setupUAAppReviewManager {
    [UAAppReviewManager setAppID:APPSTORE_ID];
    [UAAppReviewManager setDebug:YES];
}

-(void)applicationDidBecomeActive:(UIApplication *)application
{
    [UAAppReviewManager showPromptIfNecessary];
}
```
but if I call showPrompt it shows every time

**Comment by coneybeare** [comment]
showPromptIfNecessary checks all the criteria you have set against the recorded user behavior, not showing if those criteria haven't been met. I would try stepping through the checks to see where it is not being met, in order to determine why the rating prompt is not necessary yet.
