### ISSUE TITLE
"No, thanks" button showing at top, and "Rate" button at bottom: how to reverse the order?

### ISSUE THREAD

**Issue by vanderneut** [UrbanApps/UAAppReviewManager#31]
For me the alert shows up with the following three options vertically listed from top to bottom in this order:

    No, thanks
    Remind me later
    Sure

Is there a way to have the Rate button be at the top of this list and the Cancel button at the bottom of this list? Can that be achieved somehow through the UAAppReviewManager API now, or would that require a code change to UAAppReviewManager?

Thanks!
Erik

**Comment by coneybeare** [comment]
You will need to either edit the code or subclass to override [this method](https://github.com/UrbanApps/UAAppReviewManager/blob/master/UAAppReviewManager.m#L829)
