### ISSUE TITLE
No errors but lib doesn't work as it does with Cocoapods integration

### ISSUE THREAD

**Issue by catarino** [UrbanApps/UAAppReviewManager#33]
Hi Matt,

I have this strange issue. 

I've integrated UAAppReviewManager with Cocoapods, done what I had to do with my code to accomodate it and it worked like charm. Everything as expected.

What happened was that I wanted to make it work without CocoaPods integration, so that not only don't have to resort to it but mostly to keep my custom localizable strings as I need them.

So, I've integrated the files as supposed, (had some 64 arch related errors, but I fixed them with -fobjc-arc and adding StoreKit.framework) so I build everything without errors.

What happens is that it doesn't work. I've added a NSLog to check if that method was running and it is but now the alert doesn't appear.

There are no errors, warnings, etc., nothing.

Do you have any idea, what might be happening?  

Thank you so much for your work and any help in advance.

Best,
Catarino

**Comment by catarino** [comment]
if it helps, more information I can give is that I have UAAppReviewManager triggered by a button as in:

-----
UIButton *loveButton = [UIButton buttonWithType:UIButtonTypeCustom];

  loveButton.frame = CGRectMake(self.view.frame.size.width / 2.65, 20, 80, 44);
  UIImage *loveImage = [UIImage imageNamed:@"mapbuttons-Love.png"];
  [loveButton setImage:loveImage forState:UIControlStateNormal];
  loveButton.imageEdgeInsets = UIEdgeInsetsMake(6, 15, 2, 14);
  [self.view addSubview:loveButton];
  [loveButton addTarget:self
                 action:@selector(loveTapped:)
       forControlEvents:UIControlEventTouchUpInside];   

-----
where it triggers:
-----

- (void)loveTapped:(UIButton *)loveButton {

    
    //  [loveButton setHidden:YES];
   
    
    
    // The AppID is the only required setup
    [UAAppReviewManager setAppID:@"431659526"]; // iBooks
    
    // Debug means that it will popup on the next available change
    [UAAppReviewManager setDebug:YES];
    
    [UAAppReviewManager setReviewTitle:@"The Love Button"];
    
    // YES here means it is ok to show, it is the only override to Debug == YES.
    [UAAppReviewManager userDidSignificantEvent:YES];
    
    // This overrides the default value of 30, but it doesn't matter here because
    // of Debug mode enabled
    [UAAppReviewManager setDaysUntilPrompt:28];
    
    // This overrides the default value of 1, but it doesn't matter here because
    // of Debug mode enabled
    [UAAppReviewManager setDaysBeforeReminding:13];
    
    // This means that the popup won't show if you have already rated any version
    // of the app, but it doesn't matter here because of Debug mode enabled
    [UAAppReviewManager setShouldPromptIfRated:YES];
    
    // UAAppReviewManager has sensible defaults for the NSUserDefault keys it uses, but you can customize that here
    [UAAppReviewManager setKey:@"kSettingsSignificantEventTally" forUAAppReviewManagerKeyType:UAAppReviewManagerKeySignificantEventCount];
    
    // YES here means it is ok to show, but it doesn't matter because we have debug on.
    [UAAppReviewManager userDidSignificantEvent:YES];
    
    NSLog(@"Love tapped");
}

------
only thing working is the: NSLog(@"Love tapped");

(I do have Debug set to "yes") as I said it works perfectly fine with cocoapods.

really don't know what to do.

Thx in advance.

**Comment by coneybeare** [comment]
Try stepping through the code to see where exactly in `UAAppReviewManager` the logic is not acting as you expect.

**Comment by catarino** [comment]
I'm considering using cocoapods to make it work without any other problem. I mean it's working so why make it harder.
 
 thx.
