### ISSUE TITLE
[Feature request] Hide button if not setting button title

### ISSUE THREAD

**Issue by wongzigii** [UrbanApps/UAAppReviewManager#34]
I just want one or two button(s) in some case. Is there any way to hide button if I don't set button title?

**Comment by coneybeare** [comment]
From the [readme](https://github.com/UrbanApps/UAAppReviewManager/blob/master/README.md):

> The daysBeforeReminding configuration determines how many days UAAPpReviewManager will wait before reminding the user to rate again, should they select the "Remind Me Later" option on the first alert. It defaults to 1 day. A value of 0 will remove the "Remind Me Later" button and disable this feature.
