### ISSUE TITLE
Previously rated does not persist

### ISSUE THREAD

**Issue by dxdc** [UrbanApps/UAAppReviewManager#39]
If user sets: `[UAAppReviewManager setShouldPromptIfRated:NO];`

then, after next version, this will persist as follows:
`UAAppReviewManagerKeyDeclinedToRate: NO`
`UAAppReviewManagerKeyPreviousVersionDeclinedToRate: YES`

however, after the *next* version, it gets reset back as if the user had never rated it.
`UAAppReviewManagerKeyDeclinedToRate: NO`
`UAAppReviewManagerKeyPreviousVersionDeclinedToRate: NO`

I believe this should be a bug and that `UAAppReviewManagerKeyPreviousVersionDeclinedToRate` should persist.

From examining the code, this appears to also be an issue in [ArmChair](https://github.com/UrbanApps/Armchair])

**Comment by dxdc** [comment]
See https://github.com/UrbanApps/UAAppReviewManager/pull/41/commits/3c03cb307729de255062d652471d6af4f0787190#diff-800df9bf507f04a356b78ccd0d6acf52R712

**Comment by coneybeare** [comment]
Make the change indicated in the code comment and it's good to go. Thanks!
